name: CI - Build, Lint and Test Python App

on:
  push:
  pull_request:

jobs:
  ci:
    name: ğŸ”§ Build + Lint + Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout et config Python
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Installation des dÃ©pendances
      - name: Installer les dÃ©pendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lint
      - name: ğŸ” Lancer Flake8
        run: flake8

      # Tests
      - name: ğŸ§ª Lancer les tests unitaires
        run: nosetests
